version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/dusan/src/app
      - /dusan/src/app/node_modules
    command: npm run start:dev
    depends_on: 
      - postgres
    environment: 
      DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/martian
      NODE_ENV: development
      JWT_SECRET: random_jwt-secret
      MAIL_HOST: smtp.mailtrap.io
      MAIL_USERNAME: changeMe
      MAIL_PASSWORD: changeMe
      DEFAULT_ADMIN_EMAIL: admin@admin.com
      DEFAULT_ADMIN_PASSWORD: randomPasswordString1234
      PORT: 3000
    ports:
      - 3000:3000

  postgres:
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: martian
    ports:
      - 5432:5432