version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: test
    volumes:
      - .:/dusan/src/app
      - /dusan/src/app/node_modules
    command: npm run test:e2e
    depends_on: 
      - postgres
    environment:
      TEST_DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/martian_testing
      NODE_ENV: test
      JWT_SECRET: random_jwt-secret
      PORT: 3000
    ports:
      - 3000:3000

  postgres:
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: martian_testing
    ports:
      - 5432:5432